services:
  app:
    container_name: allauth_keycloak_example
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    working_dir: /workspace
    tty: true
    volumes:
      - .:/workspace:cached
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0
    ports:
      - 8080:8080
    command: ["start-dev", "--import-realm"]
    volumes:
      - keycloak-volume:/opt/keycloak/data
      - ${LOCAL_WORKSPACE_FOLDER:-./keycloak}:/opt/keycloak/data/import:ro
    restart: always
    networks:
      default:
        aliases:
          - keycloak.private
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      default:
        aliases:
          - mailhog.private
    restart: always

volumes:
  keycloak-volume: