services:
  app:
    container_name: allauth_keycloak_example
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    working_dir: /workspace
    tty: true
    volumes:
      - .:/workspace:cached
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.4
    ports:
      - 8080:8080
    command:
      - "start-dev"
    # volumes:
    #   - keycloak-volume:/opt/keycloak/data
    restart: always
    # networks:
    #   default:
    #     aliases:
    #       - keycloak.private
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin

volumes:
  keycloak-volume:
