[project]
name = "allauth-keycloak-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-allauth[openid-connect,socialaccount]>=65.2.0",
    "django<5.0",
]

[dependency-groups]
dev = [
    "ruff>=0.7.3",
]
